package CommModels.Device;

public enum RgbLedState
{
    ON_RED, ON_BLUE, ON_GREEN, ON_MAGENTA, ON_CYAN, ON_YELLOW, ON_WHITE, BLINKING_RED, BLINKING_BLUE, BLINKING_GREEN,
    BLINKING_MAGENTA, BLINKING_CYAN, BLINKING_YELLOW, BLINKING_WHITE, SPECTRUM_CYCLING, OFF
}
