package CommModels.Command;

public enum RgbLedCommandType
{
    TOGGLE_RED, TOGGLE_GREEN, TOGGLE_BLUE, TOGGLE_MAGENTA, TOGGLE_YELLOW, TOGGLE_CYAN, TOGGLE_WHITE, BLINK_RED,
    BLINK_GREEN, BLINK_BLUE, BLINK_MAGENTA, BLINK_YELLOW, BLINK_CYAN, BLINK_WHITE, SPECTRUM_CYCLE
}
